In [1]:
import torch
from torch import tensor

In [3]:
feature = tensor([[1,1,1,1]], dtype=torch.float)

In [4]:
feature

tensor([[1., 1., 1., 1.]])

In [5]:
prototype = tensor([[0,0,0,0]], dtype=torch.float)

In [6]:
prototype

tensor([[0., 0., 0., 0.]])

In [16]:
dist=torch.nn.PairwiseDistance(p=2, keepdim=True)

In [17]:
dist

PairwiseDistance()

In [18]:
dist(feature, prototype)

tensor([[2.0000]])

In [19]:
feature2 = tensor([[2,2,2,2]], dtype=torch.float)

In [20]:
features = torch.cat([feature, feature2])

In [21]:
features

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.]])

In [26]:
result = dist(features, prototype)

In [27]:
result

tensor([[2.0000],
        [4.0000]])

In [28]:
result.size()

torch.Size([2, 1])

In [25]:
torch.max(result).size()

torch.Size([])