In [1]:
import torch

In [2]:
from torch import nn

In [3]:
m = nn.Dropout(p=0.2, inplace=True)

In [4]:
x = torch.randn(20, 16)

In [5]:
x

tensor([[ 1.0355,  0.3295, -1.3254, -0.1492,  0.6075,  1.1680,  0.6419, -0.5087,
          0.3258, -1.2847, -0.3287, -0.0458, -0.0948, -0.7770,  0.2401,  0.0135],
        [ 0.2005,  0.3725, -0.6758,  1.4517,  0.1068, -0.4213, -0.3225, -0.7566,
          0.6091, -0.6553, -0.1163, -0.6895,  0.2357,  1.0178, -0.5524,  1.4188],
        [-0.4691, -1.6557, -1.0079, -1.3609,  1.4187, -0.4270,  0.6731,  0.6476,
          1.1071,  0.3513, -0.5697, -0.8418, -0.6087,  0.0260,  1.5406,  1.7551],
        [ 0.6311, -0.9900, -0.6793,  1.9252, -0.3255, -1.3874,  0.7469, -1.5846,
         -2.1252,  0.0262,  0.1944,  0.4262,  0.5623,  0.1951, -1.8351,  0.8105],
        [ 0.7092, -1.8004,  0.3367, -0.4751,  0.5611, -0.3091, -0.9987,  0.4350,
         -0.2050, -0.6687, -0.2872, -0.5715, -0.1845, -1.9165,  0.3165,  0.4272],
        [-0.7911,  2.5037,  0.4827,  1.3525, -0.9620, -2.1266, -0.9147, -0.0033,
          0.0475, -2.7373,  0.9062, -0.9098,  1.1696, -1.6485, -1.0671, -1.2883],
        [-0.0813, -0.5

In [6]:
x.size()

torch.Size([20, 16])

In [7]:
m(x)

tensor([[ 1.2944,  0.0000, -0.0000, -0.1865,  0.7594,  1.4600,  0.0000, -0.6359,
          0.4072, -1.6059, -0.4109, -0.0572, -0.0000, -0.9712,  0.3001,  0.0169],
        [ 0.2507,  0.0000, -0.8447,  0.0000,  0.1335, -0.5267, -0.4031, -0.0000,
          0.7614, -0.8191, -0.1454, -0.8619,  0.0000,  1.2723, -0.0000,  1.7735],
        [-0.5864, -2.0696, -1.2599, -1.7012,  1.7734, -0.5337,  0.8414,  0.0000,
          1.3839,  0.0000, -0.7121, -0.0000, -0.0000,  0.0000,  1.9257,  2.1938],
        [ 0.7888, -0.0000, -0.0000,  2.4065, -0.0000, -1.7343,  0.9336, -0.0000,
         -2.6565,  0.0328,  0.0000,  0.5328,  0.7029,  0.2438, -2.2939,  0.0000],
        [ 0.8865, -0.0000,  0.4209, -0.5939,  0.7013, -0.3864, -1.2484,  0.5438,
         -0.0000, -0.0000, -0.0000, -0.7144, -0.2306, -2.3957,  0.3956,  0.5340],
        [-0.9889,  3.1296,  0.6034,  1.6907, -0.0000, -2.6582, -1.1434, -0.0041,
          0.0594, -0.0000,  0.0000, -1.1372,  0.0000, -0.0000, -1.3339, -1.6103],
        [-0.1017, -0.7

In [8]:
m1 = nn.Dropout(p=0.0, inplace=True)

In [9]:
x1 = torch.randn(20, 16)

In [10]:
m1(x1)

tensor([[ 1.0200, -0.6493, -0.8672,  0.6085,  0.0517,  0.6899, -1.6227,  0.8195,
          0.3375,  0.5097, -1.0193, -1.4234,  1.1324,  1.5783,  0.4983, -0.3666],
        [ 0.4472, -0.4346,  1.4226, -1.4876, -0.3893, -0.3212,  1.9043, -0.3154,
          0.6831, -0.0806, -0.6811,  1.4793,  0.1743,  0.2168,  0.9337, -1.5710],
        [-0.2433,  0.8789, -0.5738,  0.0026, -0.6297,  0.5055, -0.3305, -0.4026,
         -1.4040,  0.4804, -0.6797, -1.4300, -1.9706, -1.6573,  0.1362,  1.7778],
        [-0.1991, -0.2440, -1.6690,  0.2906,  0.0596, -1.0604, -1.3266,  1.6830,
          0.6353, -1.1744,  0.8195,  0.2800,  0.5275, -0.2182,  0.8238,  0.7091],
        [ 0.3769, -0.2653, -0.5580,  1.8591,  0.3889,  1.0129, -0.0118, -0.6886,
         -1.1850,  1.5556,  0.1986,  1.0888,  0.6278,  1.4702, -0.3386, -0.7103],
        [-2.2646,  1.1310, -0.7166,  0.1089,  1.2319,  0.3930, -0.1887, -1.2765,
          0.5481,  0.4565,  0.8672,  0.9383, -1.5143, -0.0035,  1.4466, -0.4886],
        [-0.0107, -0.2